; generated by Flash Studio 1.7.17 on 2026-01-01 at 00:00:00
; total layer number: 308
; filament used [g] = 24.51, 10.31, 23.39, 5.11
; <filament id="1" tray_info_idx="GFG99" type="PETG" color="#000000" used_m="7.80" used_g="23.83" />
; <filament id="2" tray_info_idx="GFG99" type="PETG" color="#999999" used_m="3.33" used_g="10.16" />
; <filament id="3" tray_info_idx="GFG99" type="PETG" color="#FD8008" used_m="7.36" used_g="22.49" />
; <filament id="4" tray_info_idx="GFG99" type="PETG" color="#FD8008" used_m="1.57" used_g="4.79" />
; total filament used [g] = 63.32
; estimated printing time (normal mode) = 7h 37m 55s
; filament_colour = #000000;#999999;#FD8008;#FD8008
; filament_diameter = 1.75,1.75,1.75,1.75
; filament_settings_id = "Flashforge PETG Pro @FF C5";"Flashforge PETG Pro @FF C5";"Flashforge PETG Pro @FF C5";"Flashforge PETG Pro @FF C5"
; filament_type = PETG;PETG;PETG;PETG
; filament_vendor = Flashforge;Flashforge;Flashforge;Flashforge
; layer_height = 0.08
; nozzle_diameter = 0.4,0.4,0.4,0.4
; print_settings_id = 0.08mm Standard @FF C5
; printer_model = Flashforge Creator 5
; printer_settings_id = Flashforge Creator 5 0.4 nozzle
; CONFIG_BLOCK_END
